---
development:
  cloud_name: Rails.application.secrets.cloudinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: Rails.application.secrets.cloudinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drubv9lgc
  api_key: '248327675289238'
  api_secret: 22CrLVpPDAHoBkpFh1u354Qd1Yo
  enhance_image_tag: true
  static_image_support: false
