# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79bf597d49ff58a262b95d8cdc96dde010a154b75d64e3a1d0f4c5feafcd22b727dd062b618b50df1052036333dde682fd1594ccde6024674b91940fe52e5570
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>

test:
  secret_key_base: d292e01a070de9006cd5887d8dc76a2460b82d75b091eead7b7da74abc1b6cbaa20d698488721138d5e07bdb0a0860ffa9f9ae2f3d7d613b3e9e625ce46bfa3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
